AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation - Nested stacks - DB template.

Resources:
  MyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MyTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  TableName:
    Value: !Ref MyTable
